#!/usr/bin/env python3
"""Patches the Android project generated by `flutter create` (safe to run twice).

  - AndroidManifest.xml: INTERNET + AD_ID permissions, AdMob app id placeholder,
    no clear-text traffic, network security config, predictive-back opt-in (Android 16)
  - copies proguard-rules.pro and network_security_config.xml

The Gradle edits are shown in README.md step 4 (they are 4 small blocks).
"""
import re
import shutil
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
android = root / "android"
manifest = android / "app/src/main/AndroidManifest.xml"
if not manifest.exists():
    sys.exit("Run `flutter create --platforms=android .` first (android/ folder not found).")

text = manifest.read_text(encoding="utf-8")

def add_permission(t, name):
    if name in t:
        return t
    return re.sub(r"(<application)", f'<uses-permission android:name="{name}"/>\n    \\1', t, count=1)

text = add_permission(text, "android.permission.INTERNET")
text = add_permission(text, "com.google.android.gms.permission.AD_ID")

app_tag = re.search(r"<application[^>]*>", text, re.S).group(0)
new_tag = app_tag
if "usesCleartextTraffic" not in new_tag:
    new_tag = new_tag.replace("<application", '<application\n        android:usesCleartextTraffic="false"', 1)
if "enableOnBackInvokedCallback" not in new_tag:
    new_tag = new_tag.replace("<application", '<application\n        android:enableOnBackInvokedCallback="true"', 1)
if "networkSecurityConfig" not in new_tag:
    new_tag = new_tag.replace("<application", '<application\n        android:networkSecurityConfig="@xml/network_security_config"', 1)
text = text.replace(app_tag, new_tag, 1)

if "com.google.android.gms.ads.APPLICATION_ID" not in text:
    meta = ('    <meta-data\n'
            '            android:name="com.google.android.gms.ads.APPLICATION_ID"\n'
            '            android:value="${admobAppId}"/>\n    ')
    text = text.replace("</application>", meta + "</application>", 1)

manifest.write_text(text, encoding="utf-8")

xml_dir = android / "app/src/main/res/xml"
xml_dir.mkdir(parents=True, exist_ok=True)
shutil.copy(root / "android_patch/network_security_config.xml", xml_dir / "network_security_config.xml")
shutil.copy(root / "android_patch/proguard-rules.pro", android / "app/proguard-rules.pro")
print("Android manifest and files patched. Now do the Gradle edits from README step 4.")
